name: Multi-OS, Multi-Compiler Build

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, action ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-22.04
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    steps:
    - name: Clone gimmel-test repository
      uses: actions/checkout@v4
      with:
        repository: jaffco/gimmel-test
        submodules: recursive
    
    - name: Install gimmel-test dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libasound2-dev libjack-jackd2-dev \
          ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev \
          libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
          libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
    
    - name: Install gimmel-test dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake

    - name: Install gimmel-test dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install scipy

    - name: Init Repo
      run: |
        ./init.sh
      shell: bash

    - name: Check out current Gimmel branch
      run: |
        cd include/Gimmel
        git fetch origin
        
        # Extract branch name and handle PRs
        if [[ "${{ github.ref }}" == refs/pull/* ]]; then
          echo "PR detected, using base branch"
          git checkout ${{ github.base_ref }}
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Checking out branch: $BRANCH_NAME"
          
          # Check if branch exists on remote first
          if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
            echo "Branch $BRANCH_NAME exists on remote, checking out"
            # Fetch the specific branch and create local tracking branch
            git fetch origin $BRANCH_NAME:$BRANCH_NAME || git fetch origin $BRANCH_NAME
            git checkout $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist in Gimmel repository, staying on default branch"
            echo "Available branches:"
            git branch -r
          fi
        fi
      shell: bash

    - name: Build Plugin
      run: |
        ./run.sh
      shell: bash
    
    - name: List build artifacts
      run: |
        echo "Build directory contents:"
        find build -name "*.vst3" -o -name "*.component" -o -name "*.app" -o -name "*.exe" 2>/dev/null || true
        ls -la build/GIMMEL-TEST_artefacts/ 2>/dev/null || true
      shell: bash
